### PR TITLE
Add black game board 

### PR DESCRIPTION
**Pull request by De3up**
1.Game board in Main.hs
2.Add gloss in package.yaml

---
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)

### CODE REVIEW

**Comment by cblp** [comment]
Содержание не соответствует заголовку. Не тот коммит.

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[app/Main.hs, line 7 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDIT85wCPfC7daDp5nm:-LDIT85wCPfC7daDp5nn:bz7qowt) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L7)):*
> ```Haskell
> main :: IO ()
> main =
>   play display bgColor fps initialWorld renderWorld handleWorld updateWorld
> ```

добавь 2 пробела, чтобы отступ был 4

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDITPz23lHfb_ByRO4v:bov4eb3) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
> ```Haskell
> module Main  where
> ```

зачем?

---

*[app/Main.hs, line 4 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITGly5nyuMENKK8FP:-LDITGly5nyuMENKK8FQ:barj5oj) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L4)):*
> ```Haskell
> 
> 
> import Graphics.Gloss.Interface.Pure.Game
> ```

Добавь пустую строку между импортом и функцией

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/Main.hs, line 9 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITY6BAwG9z0bucZsr:-LDITY6BAwG9z0bucZss:bv520g8) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L9)):*
> ```Haskell
>   play display bgColor fps initialWorld renderWorld handleWorld updateWorld
>   where
>     display = InWindow "Game of Tron" winSize winOffset
> ```

может, "Game of Trons" будет смешнее?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDIpkKpEWq1Sxmbb60b:b3cncja) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

зачем?
</blockquote></details>

Зачем что? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 4 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITGly5nyuMENKK8FP:-LDIps9g5NVQYTfJe_CX:b7ara9n) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L4)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Добавь пустую строку между импортом и функцией
</blockquote></details>

Окей 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 7 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDIT85wCPfC7daDp5nm:-LDIputk73Azs8Em87My:b33k4h) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L7)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

добавь 2 пробела, чтобы отступ был 4
</blockquote></details>

Ок

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 9 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITY6BAwG9z0bucZsr:-LDIpwfu1iF1CoEkbgax:b13atiq) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L9)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

может, "Game of Trons" будет смешнее?
</blockquote></details>

Это небольшая отсылка :D

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDIqajV7qjhs04ko8OP:bagyj50) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Зачем что? 
</blockquote></details>

Зачем сделано это изменение?

---

*[app/Main.hs, line 9 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITY6BAwG9z0bucZsr:-LDIr-ppC-jKzuwMghNH:b-jtd852) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L9)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Это небольшая отсылка :D
</blockquote></details>

Да, я предлагаю сделать её потолще. Или это отсылка к чему-то другому?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlPEEuDMRcZd3q_uTw:bnu5l9h) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
> ```Haskell
>     fps = 60
>     initialWorld = ()
>     renderWorld  _ =  blank
> ```

Между одним пробелом и двумя нет разницы. Убери лишние.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 9 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITY6BAwG9z0bucZsr:-LDlS_Bs8FntjlKpA_1h:b-w7nczi) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L9)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Да, я предлагаю сделать её потолще. Или это отсылка к чему-то другому?
</blockquote></details>

Потолще? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDlSfey2IDRFLJLbLHH:b-r4769g) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Зачем сделано это изменение?
</blockquote></details>

А что за изменение ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDlUBqF-6eq7PV_Jc9m:b-hmknyp) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

А что за изменение ? 
</blockquote></details>

Понял, пробел :\

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlUfQN3m1_72PXCJcF:bs7wumb) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Между одним пробелом и двумя нет разницы. Убери лишние.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 9 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITY6BAwG9z0bucZsr:-LDlUeWU-BVS0X1YAJo3:b-896fix) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L9)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Потолще? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 1 at r2](https://reviewable.io/reviews/mcl1303/tron/3#-LDITPz23lHfb_ByRO4u:-LDlUdxw85N1RbpeQqPT:b-896fix) ([raw file](https://github.com/mcl1303/tron/blob/0a6cfbc3ff9d29f98cfdc7fd3b8e1dc89c97c999/app/Main.hs#L1)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Понял, пробел :\
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlVgpP8ANPfVkiM_2P:b-8kihzc) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Надо убрать пробелы, а ты добавляешь ещё больше.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlXAJxBBMjEqRdBTJ6:bygorze) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Надо убрать пробелы, а ты добавляешь ещё больше.
</blockquote></details>

Ещё 2 лишних осталось

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by De3up** [comment]
*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlYsWo88lrFwtjMqlq:b-jltwwu) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Ещё 2 лишних осталось
</blockquote></details>

Убрал 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/Main.hs, line 14 at r4](https://reviewable.io/reviews/mcl1303/tron/3#-LDlPEEuDMRcZd3q_uTv:-LDlZU7S92UtVfvoLoUD:b-g1zjhq) ([raw file](https://github.com/mcl1303/tron/blob/b527311e3904c7e18178f82b3ae97524b1b37431/app/Main.hs#L14)):*
<details><summary><i>Previously, De3up wrote…</i></summary><blockquote>

Убрал 
</blockquote></details>

1 лишний пробел остался — между именем функции и аргументом

---


*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mcl1303/tron/3)*

**Pull request merged**
